package net.yyc12345.teyvatcraft.blocks;

import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.FlowerBlock;
import net.minecraft.block.Material;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.sound.BlockSoundGroup;

public class TeyvatFlowerLikePlantBlock extends FlowerBlock {
    public TeyvatFlowerLikePlantBlock() {
        super(StatusEffects.LUCK, 1, FabricBlockSettings.of(Material.PLANT).noCollision().breakInstantly().sounds(BlockSoundGroup.GRASS));
    }
}
